// types
const PLAYER_SCORED = 'game/PLAYER_SCORED';
const RESET_MATCH = 'game/RESET_MATCH';
const PLAYER_SCORED_GAME = 'game/PLAYER_SCORED_GAME';
const PLAYER_SCORED_SET = 'game/PLAYER_SCORED_SET';
const PLAYER_SCORED_MATCH = 'game/PLAYER_SCORED_MATCH';

const PLAYERS = {
  PLAYER_ONE: 'Player One',
  PLAYER_TWO: 'Player Two',
};

const VALID_POINTS = ['0', '15', '30', '40', 'Adv', 'Win'];

export {
  PLAYER_SCORED,
  RESET_MATCH,
  PLAYER_SCORED_GAME,
  PLAYERS,
  VALID_POINTS,
  PLAYER_SCORED_SET,
  PLAYER_SCORED_MATCH,
};
